name: inno-deck
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
services:
  - name: inno-deck
    github:
      branch: main
      repo: InnoDeck/InnoDeck
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
