spec:
  name: inno-deck
  region: sfo
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
  services:
    - name: inno-deck
      github:
        branch: main
        repo: InnoDeck/InnoDeck
        deploy_on_push: true
      build_command: npm run build
      run_command: node main.js
  envs:
    - key: DIGITAL_OCEAN
    - value: 1
