name: OnPushEslint
run-name: Lint ${{ github.actor }}' latest code
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.9.0'
      - run: meteor npm install
      - run: meteor npm run lint
